controller_manager:
  ros__parameters:
    update_rate: 100  # Match Gazebo physics update rate
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - first_wheel_joint
      - second_wheel_joint
      - third_wheel_joint
      - fourth_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    gains:  # Add basic PID gains for stability
      first_wheel_joint: {p: 0.5, i: 0.01, d: 0.1}
      second_wheel_joint: {p: 0.5, i: 0.01, d: 0.1}
      third_wheel_joint: {p: 0.5, i: 0.01, d: 0.1}
      fourth_wheel_joint: {p: 0.5, i: 0.01, d: 0.1}
    state_publish_rate: 100.0
    action_monitor_rate: 100.0
    interpolation_duration: 0.2